require("Baseless")

require("helpers.MergeTables")

-- Prototype Hierarchy
require("helpers.CreatePrototype")
  require("helpers.CreateItem")
    require("helpers.CreateItemWithLabel")
      require("helpers.CreateItemWithInventory")
      require("helpers.CreateItemWithTags")
      require("helpers.CreateSelectionTool")
    require("helpers.CreateTool")
  require("helpers.CreateEntity")
    require("helpers.CreateCorpse")
    require("helpers.CreateEntityWithHealth")
      require("helpers.CreateCombinator")
      require("helpers.CreateContainer")
        require("helpers.CreateLogisticContainer")
      require("helpers.CreateCraftingMachine")
        require("helpers.CreateAssemblingMachine")
      require("helpers.CreateFlyingRobot")
        require("helpers.CreateRobotWithLogisticInterface")
      require("helpers.CreatePipe")
      require("helpers.CreateRail")
      require("helpers.CreateRailSignalBase")
      require("helpers.CreateTransportBeltConnectable")
      require("helpers.CreateTurret")
      require("helpers.CreateVehicle")
        require("helpers.CreateRollingStock")
    require("helpers.CreateExplosion")
    require("helpers.CreateSmoke")
  require("helpers.CreateEquipment")

-- Items
require("prototypes.item.ammo")
require("prototypes.item.armor")
require("prototypes.item.blueprint")
require("prototypes.item.blueprint-book")
require("prototypes.item.capsule")
require("prototypes.item.copy-paste-tool")
require("prototypes.item.deconstruction-item")
require("prototypes.item.gun")
require("prototypes.item.item")
require("prototypes.item.item-with-entity-data")
require("prototypes.item.item-with-inventory")
require("prototypes.item.item-with-label")
require("prototypes.item.item-with-tags")
require("prototypes.item.mining-tool")
require("prototypes.item.module")
require("prototypes.item.rail-planner")
require("prototypes.item.repair-tool")
require("prototypes.item.selection-tool")
require("prototypes.item.tool")
require("prototypes.item.upgrade-item")

-- Entities (depends on above)


-- Entities
require("prototypes.entity.accumulator")
require("prototypes.entity.ammo-turret")
require("prototypes.entity.arithmetic-combinator")
require("prototypes.entity.arrow")
require("prototypes.entity.artillery-flare")
require("prototypes.entity.artillery-projectile")
require("prototypes.entity.artillery-turret")
require("prototypes.entity.artillery-wagon")
require("prototypes.entity.assembling-machine")
require("prototypes.entity.beacon")
require("prototypes.entity.beam")
require("prototypes.entity.boiler")
require("prototypes.entity.burner-generator")
require("prototypes.entity.car")
require("prototypes.entity.cargo-wagon")
require("prototypes.entity.character")
require("prototypes.entity.character-corpse")
require("prototypes.entity.cliff")
require("prototypes.entity.combat-robot")
require("prototypes.entity.constant-combinator")
require("prototypes.entity.construction-robot")
require("prototypes.entity.container")
require("prototypes.entity.corpse")
require("prototypes.entity.decider-combinator")
require("prototypes.entity.deconstructible-tile-proxy")
require("prototypes.entity.decorative")
require("prototypes.entity.electric-energy-interface")
require("prototypes.entity.electric-pole")
require("prototypes.entity.electric-turret")
require("prototypes.entity.entity-ghost")
require("prototypes.entity.explosion")
require("prototypes.entity.fire")
require("prototypes.entity.fish")
require("prototypes.entity.flame-thrower-explosion")
require("prototypes.entity.fluid-turret")
require("prototypes.entity.fluid-wagon")
require("prototypes.entity.flying-text")
require("prototypes.entity.furnace")
require("prototypes.entity.gate")
require("prototypes.entity.generator")
require("prototypes.entity.heat-interface")
require("prototypes.entity.heat-pipe")
require("prototypes.entity.highlight-box")
require("prototypes.entity.infinity-container")
require("prototypes.entity.infinity-pipe")
require("prototypes.entity.inserter")
require("prototypes.entity.item-entity")
require("prototypes.entity.item-request-proxy")
require("prototypes.entity.lab")
require("prototypes.entity.lamp")
require("prototypes.entity.land-mine")
require("prototypes.entity.leaf-particle")
require("prototypes.entity.loader")
require("prototypes.entity.loader-1x1")
require("prototypes.entity.locomotive")
require("prototypes.entity.logistic-container")
require("prototypes.entity.logistic-robot")
require("prototypes.entity.market")
require("prototypes.entity.mining-drill")
require("prototypes.entity.offshore-pump")
require("prototypes.entity.particle")
require("prototypes.entity.particle-source")
require("prototypes.entity.pipe")
require("prototypes.entity.pipe-to-ground")
require("prototypes.entity.player-port")
require("prototypes.entity.power-switch")
require("prototypes.entity.programmable-speaker")
require("prototypes.entity.projectile")
require("prototypes.entity.pump")
require("prototypes.entity.radar")
require("prototypes.entity.rail-chain-signal")
require("prototypes.entity.rail-remnants")
require("prototypes.entity.rail-signal")
require("prototypes.entity.reactor")
require("prototypes.entity.resource")
require("prototypes.entity.roboport")
require("prototypes.entity.rocket-silo")
require("prototypes.entity.rocket-silo-rocket-shadow")
require("prototypes.entity.simple-entity")
require("prototypes.entity.simple-entity-with-force")
require("prototypes.entity.simple-entity-with-owner")
require("prototypes.entity.smoke")
require("prototypes.entity.smoke-with-trigger")
require("prototypes.entity.solar-panel")
require("prototypes.entity.speech-bubble")
require("prototypes.entity.splitter")
require("prototypes.entity.sticker")
require("prototypes.entity.storage-tank")
require("prototypes.entity.stream")
require("prototypes.entity.tile-ghost")
require("prototypes.entity.train-stop")
require("prototypes.entity.transport-belt")
require("prototypes.entity.tree")
require("prototypes.entity.turret")
require("prototypes.entity.underground-belt")
require("prototypes.entity.unit-spawner")
require("prototypes.entity.wall")

-- Equipment
require("prototypes.equipment.active-defense-equipment")
require("prototypes.equipment.battery-equipment")
require("prototypes.equipment.belt-immunity-equipment")
require("prototypes.equipment.energy-shield-equipment")
require("prototypes.equipment.generator-equipment")
require("prototypes.equipment.movement-bonus-equipment")
require("prototypes.equipment.night-vision-equipment")
require("prototypes.equipment.roboport-equipment")
require("prototypes.equipment.solar-panel-equipment")

-- Items (depends on above)
require("prototypes.item.science")

-- Entities (depends on above)
require("prototypes.entity.curved-rail")
require("prototypes.entity.rocket-silo-rocket")
require("prototypes.entity.straight-rail")
require("prototypes.entity.unit")

-- Categories (depends on above)
require("prototypes.category.ammo")
require("prototypes.category.damage")
require("prototypes.category.equipment")
require("prototypes.category.fuel")
require("prototypes.category.module")
require("prototypes.category.recipe")
require("prototypes.category.resource")
require("prototypes.category.trigger-target")

-- Other (depends on above)
require("prototypes.item-group")
require("prototypes.item.copper-cable")
require("prototypes.item.green-wire")
require("prototypes.item.red-wire")
require("prototypes.other.equipment-grid")
require("prototypes.other.fluid")
require("prototypes.other.optimized-particle")
require("prototypes.other.tile")
require("prototypes.other.trivial-smoke")
require("prototypes.other.virtual-signal")
