CreateEntityWithHealth("character", {
  animations =
  {
    {
      idle = Baseless.RotatedAnimation,
      idle_with_gun = Baseless.RotatedAnimation,
      running = Baseless.RotatedAnimation,
      running_with_gun = Baseless.RotatedAnimation,
      mining_with_tool = Baseless.RotatedAnimation,
    },
  },
  build_distance = 0,
  damage_hit_tint = Baseless.Color,
  distance_per_frame = 0,
  drop_item_distance = 0,
  eat = Baseless.Sound,
  heartbeat = Baseless.Sound,
  inventory_size = 0,
  item_pickup_distance = 0,
  loot_pickup_distance = 0,
  maximum_corner_sliding_distance = 0,
  mining_speed = 0,
  mining_with_tool_particles_animation_positions = {},
  reach_distance = 0,
  reach_resource_distance = 0,
  running_sound_animation_positions = {},
  running_speed = 0,
  ticks_to_keep_aiming_direction = 0,
  ticks_to_keep_gun = 0,
  ticks_to_stay_in_combat = 0,
})
