CreateEntityWithHealth("inserter", {
  energy_source = Baseless.EnergySource.Void,
  extension_speed = 1,
  hand_base_picture = Baseless.Sprite,
  hand_base_shadow = Baseless.Sprite,
  hand_closed_picture = Baseless.Sprite,
  hand_closed_shadow = Baseless.Sprite,
  hand_open_picture = Baseless.Sprite,
  hand_open_shadow = Baseless.Sprite,
  insert_position = {0, 1},
  pickup_position = {0, -1},
  platform_picture = Baseless.Sprite4Way,
  rotation_speed = 1,
  collision_box = {{-0.1, -0.1}, {0.1, 0.1}},
})
