CreateEntityWithHealth("roboport", {
  base = Baseless.Sprite,
  base_animation = Baseless.Animation,
  base_patch = Baseless.Sprite,
  charge_approach_distance = 1,
  charging_energy = "1W",
  construction_radius = 1,
  door_animation_down = Baseless.Animation,
  door_animation_up = Baseless.Animation,
  energy_source = Baseless.EnergySource.Void,
  energy_usage = "1W",
  logistics_radius = 1,
  material_slots_count = 0,
  recharge_minimum = "1W",
  recharging_animation = Baseless.Animation,
  request_to_open_door_timeout = 1,
  robot_slots_count = 0,
  spawn_and_station_height = 1,
})
