if Baseless.Needs.RocketEntity then
  CreateEntity("rocket-silo-rocket", {
    effects_fade_in_end_distance = 1,
    effects_fade_in_start_distance = 1,
    engine_starting_speed = 1,
    flying_acceleration = 1,
    flying_speed = 1,
    full_render_layer_switch_distance = 1,
    inventory_size = 1,
    rising_speed = 1,
    rocket_flame_animation = Baseless.Animation,
    rocket_flame_left_animation = Baseless.Animation,
    rocket_flame_left_rotation = 1,
    rocket_flame_right_animation = Baseless.Animation,
    rocket_flame_right_rotation = 1,
    rocket_glare_overlay_sprite = Baseless.Sprite,
    rocket_launch_offset = {0, 0},
    rocket_render_layer_switch_distance = 1,
    rocket_rise_offset = {0, 0},
    rocket_shadow_sprite = Baseless.Sprite,
    rocket_smoke_bottom1_animation = Baseless.Animation,
    rocket_smoke_bottom2_animation = Baseless.Animation,
    rocket_smoke_top1_animation = Baseless.Animation,
    rocket_smoke_top2_animation = Baseless.Animation,
    rocket_smoke_top3_animation = Baseless.Animation,
    rocket_sprite = Baseless.Sprite,
    rocket_visible_distance_from_center = 1,
    shadow_fade_out_end_ratio = 1,
    shadow_fade_out_start_ratio = 1
  })
end
