if CreateAssemblingMachine("rocket-silo", {
  active_energy_usage = "1W",
  arm_01_back_animation = Baseless.Animation,
  arm_02_right_animation = Baseless.Animation,
  arm_03_front_animation = Baseless.Animation,
  base_day_sprite = Baseless.Sprite,
  base_front_sprite = Baseless.Sprite,
  door_back_open_offset = {0, 0},
  door_back_sprite = Baseless.Sprite,
  door_front_open_offset = {0, 0},
  door_front_sprite = Baseless.Sprite,
  door_opening_speed = 1,
  energy_usage = "1W",
  hole_clipping_box = Baseless.BoundingBox,
  hole_light_sprite = Baseless.Sprite,
  hole_sprite = Baseless.Sprite,
  idle_energy_usage = "1W",
  lamp_energy_usage = "1W",
  light_blinking_speed = 1,
  red_lights_back_sprites = Baseless.Sprite,
  red_lights_front_sprites = Baseless.Sprite,
  rocket_entity = "dummy-rocket-silo-rocket",
  rocket_glow_overlay_sprite = Baseless.Sprite,
  rocket_parts_required = 1,
  rocket_shadow_overlay_sprite = Baseless.Sprite,
  satellite_animation = Baseless.Animation,
  satellite_shadow_animation = Baseless.Animation,
  shadow_sprite = Baseless.Sprite,
  silo_fade_out_end_distance = 1,
  silo_fade_out_start_distance = 1,
  times_to_blink = 1,
}) then
  Baseless.Needs.RocketEntity = true
end
